### ISSUE TITLE
pynsxt is required for this module

### ISSUE THREAD

**Issue by sinu** [yasensim/nsxt-ansible#12]
Hello 
I am getting pynsxt is required for this module,
what is this module can you tell me how we can install this

**Comment by yasensim** [comment]
I have updated the README on the main page. It should help!

**Comment by yasensim** [comment]
@sinu  I dont know what you are trying to run. From the error it looks like you are providing an overlay_tz_name attribute which is something I cannot find in the examples or in the code. Please provide output from your yaml spec.

**Comment by sinu** [comment]
sorry am not an expert in ansible 
Please check the  configure_nsx.yml you can see 


[root@host test]# less hosts | grep overlay_tz_name
overlay_tz_name="tz1"
[root@host test]# ansible-playbook ./configure_nsx.yml


PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [NSX-T Overlay Transport Zone] *********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'overlay_tz_name'\n\nThe error appears to have been in '/var/named/sc/test/configure_nsx.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: NSX-T Overlay Transport Zone\n      ^ here\n"}
        to retry, use: --limit @/var/named/sc/test/configure_nsx.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by yasensim** [comment]
@sinu it is not because of the version. You want to use some variables from the hosts file but you did not instruct ansible to use this file. You have two options:
1. copy hosts file to /etc/ansible OR
2. run ansible-playbook -i hosts configure_nsx.yml

**Comment by yasensim** [comment]
I hope you managed it. I am closing this issue
