### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by liquidat** [yasensim/nsxt-ansible#37]
How about you submit those upstream?

**Comment by yasensim** [comment]
@liquidat we plan to upstream another set of modules soon where we removed the nsxt-python-sdk dependancy.

**Comment by liquidat** [comment]
@yasensim Sounds good - are those already available somewhere?

**Comment by yasensim** [comment]
not yet but coming soon

**Comment by liquidat** [comment]
Closing after a few years, is probably not gonna happen.
