### ISSUE TITLE
Provide example with just single var file

### ISSUE THREAD

**Issue by yasensim** [yasensim/nsxt-ansible#7]
Complete deploy example with all configurable variables in the hosts file.

**Comment by guillierf** [comment]
Parameters:


NSX Manager section:
-ESXi cluster
-Virtual Switch P-G
-Datastore

NSX Controllers section:
-Number of NSX controllers
-ESXi cluster
-Virtual Switch P-G
-Datastore


NSX Edge section:
-Number of NSX Edges
- Edge VM size
-ESXi cluster
-Virtual Switch P-G for MGMT
-Virtual Switch P-G for UPLINK
-Virtual Switch P-G for VTEP
-Datastore


Uplink Profiles:
-ESXI TN: VLAN-id
-ESXI TN: PNICs
-Edge TN: VLAN-id
-Edge TN: vNIC for VTEP
